version: "3"
services:
  db:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_ROOT_USERNAME:-root}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_ROOT_PASSWORD:-root}"
    volumes:
      - ./database/mongod.conf:/etc/mongod.conf
      - ./database/data/db:/data/db
      - ./database/data/log:/var/log/mongodb
    ports:
      - '27019:27019'
    command: 
      - "-f"
      - "/etc/mongod.conf"
    restart: "always"
  server:
    build: ./server
    environment: 
      MONGODB_URI: "${MONGODB_URI:-mongodb://root:root@mongo:27019/events?authSource=admin}"
    depends_on: 
      - db
    ports:
      - 3000:3000
    restart: "always"
  client:
    build: ./client
    ports:
      - 8080:80