export interface RootState {
  version: string;
}

export const MutationTypes = {
  UPDATE_EVENTS: 'UPDATE_EVENTS',
  DELETE_EVENT: 'DELETE_EVENT',
  UPDATE_EDIT_EVENT: 'UPDATE_EDIT_EVENT',
  UPDATE_TITLE: 'UPDATE_TITLE',
  UPDATE_DESCRIPTION: 'UPDATE_DESCRIPTION',
  UPDATE_DATE: 'UPDATE_DATE',
  CLEAR_EDIT_EVENT: 'CLEAR_EDIT_EVENT',
};
